# Generated by Django 5.2.3 on 2025-06-27 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Upload 3D model (GLTF, GLB, OBJ)', null=True, upload_to='3d_models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gltf', 'glb', 'obj'])]),
        ),
    ]
