# Generated by Django 5.2.3 on 2025-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_building_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/'),
        ),
    ]
