# Generated by Django 5.2.3 on 2025-07-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appuser_company_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='building_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display the images')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.building')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
