# Generated by Django 5.2.3 on 2025-07-25 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_buildingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Upload an image for the building (JPEG, PNG, GIF, WEBP)', null=True, upload_to='building_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
